using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CourseWork.Migrations
{
    /// <inheritdoc />
    public partial class AddProfilePictureToUser : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Use raw SQL for columns that might already exist in production due to manual sync or previous partial deploys
            migrationBuilder.Sql("ALTER TABLE \"Orders\" ADD COLUMN IF NOT EXISTS \"DiscountAmount\" numeric(18,2) NOT NULL DEFAULT 0.0;");
            migrationBuilder.Sql("ALTER TABLE \"AspNetUsers\" ADD COLUMN IF NOT EXISTS \"TotalSpent\" numeric(18,2) NOT NULL DEFAULT 0.0;");

            migrationBuilder.AddColumn<string>(
                name: "ProfilePictureUrl",
                table: "AspNetUsers",
                type: "text",
                nullable: true);

            migrationBuilder.Sql("CREATE TABLE IF NOT EXISTS \"UserPromotions\" (" +
                "\"Id\" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "\"ApplicationUserId\" text NOT NULL, " +
                "\"PromotionId\" integer NOT NULL, " +
                "\"IsUsed\" boolean NOT NULL, " +
                "CONSTRAINT \"FK_UserPromotions_AspNetUsers_ApplicationUserId\" FOREIGN KEY (\"ApplicationUserId\") REFERENCES \"AspNetUsers\" (\"Id\") ON DELETE CASCADE, " +
                "CONSTRAINT \"FK_UserPromotions_Promotions_PromotionId\" FOREIGN KEY (\"PromotionId\") REFERENCES \"Promotions\" (\"Id\") ON DELETE CASCADE);");

            migrationBuilder.Sql("CREATE INDEX IF NOT EXISTS \"IX_UserPromotions_ApplicationUserId\" ON \"UserPromotions\" (\"ApplicationUserId\");");
            migrationBuilder.Sql("CREATE INDEX IF NOT EXISTS \"IX_UserPromotions_PromotionId\" ON \"UserPromotions\" (\"PromotionId\");");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "UserPromotions");

            migrationBuilder.DropColumn(
                name: "DiscountAmount",
                table: "Orders");

            migrationBuilder.DropColumn(
                name: "ProfilePictureUrl",
                table: "AspNetUsers");

            migrationBuilder.DropColumn(
                name: "TotalSpent",
                table: "AspNetUsers");
        }
    }
}
